/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author WILSON ROBAYO
 */
public class ADVERTENCIA extends javax.swing.JFrame {

    /**
     * Creates new form ADVERTENCIA
     */
    public ADVERTENCIA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menugeneral = new javax.swing.JPanel();
        titulomenu = new javax.swing.JLabel();
        botoninicio = new javax.swing.JButton();
        botoninformacionestudiante = new javax.swing.JComboBox<>();
        botonmatricula = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        paneldeusuario = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        nombreusuario = new javax.swing.JLabel();
        cargousuario = new javax.swing.JLabel();
        logosacrumenu = new javax.swing.JLabel();
        logousuario = new javax.swing.JLabel();
        titulosacru4 = new javax.swing.JLabel();
        panelderechoblanco = new javax.swing.JPanel();
        derechosutexto = new javax.swing.JLabel();
        botonayuda = new javax.swing.JButton();
        nodisponible = new javax.swing.JLabel();
        mensajeensolicitarrecibo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menugeneral.setBackground(new java.awt.Color(0, 0, 0));

        titulomenu.setForeground(new java.awt.Color(255, 255, 255));
        titulomenu.setText("MENÚ GENERAL.");

        botoninicio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        botoninicio.setText("Inicio.");

        botoninformacionestudiante.setEditable(true);
        botoninformacionestudiante.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        botoninformacionestudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Información personal." }));
        botoninformacionestudiante.setToolTipText("");
        botoninformacionestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninformacionestudianteActionPerformed(evt);
            }
        });

        botonmatricula.setEditable(true);
        botonmatricula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        botonmatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matrícula." }));
        botonmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmatriculaActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout menugeneralLayout = new javax.swing.GroupLayout(menugeneral);
        menugeneral.setLayout(menugeneralLayout);
        menugeneralLayout.setHorizontalGroup(
            menugeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoninicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menugeneralLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(titulomenu)
                .addContainerGap(79, Short.MAX_VALUE))
            .addComponent(botoninformacionestudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(jSeparator6)
            .addComponent(botonmatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator5)
        );
        menugeneralLayout.setVerticalGroup(
            menugeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menugeneralLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(titulomenu)
                .addGap(18, 18, 18)
                .addComponent(botoninicio)
                .addGap(6, 6, 6)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(botoninformacionestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneldeusuario.setBackground(new java.awt.Color(0, 0, 0));
        paneldeusuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        paneldeusuario.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 94, 271, 10));

        nombreusuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreusuario.setText("NOMBRE ESTUDIANTE");
        paneldeusuario.add(nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 23, -1, -1));

        cargousuario.setForeground(new java.awt.Color(255, 255, 255));
        cargousuario.setText("ESTUDIANTE-PREGRADO.");
        paneldeusuario.add(cargousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 48, -1, -1));

        logosacrumenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosacrudef.png"))); // NOI18N
        paneldeusuario.add(logosacrumenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        logousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        paneldeusuario.add(logousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        titulosacru4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulosacru4.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru4.setText("SACRU");
        paneldeusuario.add(titulosacru4, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 36, -1, -1));

        panelderechoblanco.setBackground(new java.awt.Color(255, 255, 255));

        derechosutexto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechosutexto.setForeground(new java.awt.Color(0, 0, 0));
        derechosutexto.setText("Universidad de los Llanos © Todos los derechos reservados ");

        botonayuda.setText("Ayuda.");

        nodisponible.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        nodisponible.setForeground(new java.awt.Color(255, 0, 0));
        nodisponible.setText("PERMISO DENEGADO");

        mensajeensolicitarrecibo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mensajeensolicitarrecibo.setForeground(new java.awt.Color(255, 0, 0));
        mensajeensolicitarrecibo.setText("La opción de solicitar recibo no está disponible por el momento.");

        javax.swing.GroupLayout panelderechoblancoLayout = new javax.swing.GroupLayout(panelderechoblanco);
        panelderechoblanco.setLayout(panelderechoblancoLayout);
        panelderechoblancoLayout.setHorizontalGroup(
            panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelderechoblancoLayout.createSequentialGroup()
                .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelderechoblancoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(mensajeensolicitarrecibo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelderechoblancoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(derechosutexto)
                            .addGroup(panelderechoblancoLayout.createSequentialGroup()
                                .addComponent(nodisponible)
                                .addGap(192, 192, 192)
                                .addComponent(botonayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelderechoblancoLayout.setVerticalGroup(
            panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelderechoblancoLayout.createSequentialGroup()
                .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelderechoblancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonayuda))
                    .addGroup(panelderechoblancoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeensolicitarrecibo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(derechosutexto))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menugeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneldeusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelderechoblanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menugeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneldeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelderechoblanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoninformacionestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninformacionestudianteActionPerformed
//        INFOESTUDIANTE a = new INFOESTUDIANTE();
//        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoninformacionestudianteActionPerformed

    private void botonmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmatriculaActionPerformed
        //   SOLICITARMATRICUL b = new SOLICITARMATRICUL();
        // b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonmatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADVERTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADVERTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADVERTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADVERTENCIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADVERTENCIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonayuda;
    private javax.swing.JComboBox<String> botoninformacionestudiante;
    private javax.swing.JButton botoninicio;
    private javax.swing.JComboBox<String> botonmatricula;
    private javax.swing.JLabel cargousuario;
    private javax.swing.JLabel derechosutexto;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logosacrumenu;
    private javax.swing.JLabel logousuario;
    private javax.swing.JLabel mensajeensolicitarrecibo;
    private javax.swing.JPanel menugeneral;
    private javax.swing.JLabel nodisponible;
    private javax.swing.JLabel nombreusuario;
    private javax.swing.JPanel panelderechoblanco;
    private javax.swing.JPanel paneldeusuario;
    private javax.swing.JLabel titulomenu;
    private javax.swing.JLabel titulosacru4;
    // End of variables declaration//GEN-END:variables
}
