/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Clases.Estudiante;
import Clases.Liquidacionderecibo;
import Clases.Login;
import Clases.generarpdf;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import conexion.conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ventanas.LOGIN;

/**
 *
 * @author Santiago Suárez
 */
public class INICIOESTUDIANTE extends javax.swing.JFrame {

    conexion objconexion = new conexion();

    public static String usuario_online = "";

    /**
     * Creates new form INICIOADMIN
     */
    public INICIOESTUDIANTE() {

        initComponents();
        LOGIN objLOGIN = new LOGIN();
        //pasar el usuario online de LOGIN
        nombreusuario.setText(objLOGIN.usuario_online);
        usuario_online = nombreusuario.getText();
        objconexion.conexiones();

        Estudiante obj = recibir_usuario(usuario_online);
        System.out.println(obj.getNumero_documento());
        panelsolicitarmatricula.setVisible(false);
        panelinfoestudiante.setVisible(false);
        panelfondoinicioblanco1.setVisible(true);
        ///PARA CENTRAR LA VENTANA
        this.setLocationRelativeTo(null);
        ///PARA QUITAR EL MAXIMAR DE LA VENTANA
        this.setResizable(false);
        // recibir_usuario(usuario);

    }

    public Estudiante recibir_usuario(String usuario) {
        Login objlogin = new Login();

        Estudiante objest = objlogin.obtener_info_estudiante(usuario, objconexion);

        nombreusuario.setText(objest.getNombre_1() + " " + objest.getNombre_2() + " " + objest.getApellido_1() + " " + objest.getApellido_2());
        nombrecompleto.setText(objest.getNombre_1() + " " + objest.getNombre_2() + "" + objest.getApellido_1() + " " + objest.getApellido_2());
        tipodocumento.setText(objest.getTipo_documento());
        numerodocumento.setText(objest.getNumero_documento());
        correopersonal.setText(objest.getCorreo_personal());
        correoinstitucional.setText(objest.getCorreo_institucional());
        estado.setText(objest.getEstado());
        programa.setText(objest.getObjprograma().getNombre());
        facultad.setText(objest.getObjprograma().getObjfacultad().getNombre());
        nombre_programa.setText(objest.getObjprograma().getNombre());

        return objest;
    }

////PARA CAMBIAR EL ICONO DE LA VENTANA
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logosacru2.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneldeusuario = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        nombreusuario = new javax.swing.JLabel();
        cargousuario = new javax.swing.JLabel();
        logosacrumenu = new javax.swing.JLabel();
        logousuario = new javax.swing.JLabel();
        titulosacru4 = new javax.swing.JLabel();
        menugeneral = new javax.swing.JPanel();
        titulomenu = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        botoninicio = new javax.swing.JButton();
        botoninfoestudiante = new javax.swing.JButton();
        botonmatricula = new javax.swing.JButton();
        panelfondoinicioblanco = new javax.swing.JPanel();
        panelfondoinicioblanco1 = new javax.swing.JPanel();
        derechossacruagregarestudiante = new javax.swing.JLabel();
        titulosacru2 = new javax.swing.JLabel();
        titulosacru3 = new javax.swing.JLabel();
        botoncontacto = new javax.swing.JButton();
        botoncerrarsesion = new javax.swing.JButton();
        panelinfoestudiante = new javax.swing.JPanel();
        informacionpersonalestudiante = new javax.swing.JLabel();
        botonayuda2 = new javax.swing.JButton();
        derechossacruagregarestudiante2 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombrecompleto = new javax.swing.JLabel();
        tipodocumento = new javax.swing.JLabel();
        tipodedocumento = new javax.swing.JLabel();
        titulosacru12 = new javax.swing.JLabel();
        numerodocumento = new javax.swing.JLabel();
        correopersonal = new javax.swing.JLabel();
        titulosacru13 = new javax.swing.JLabel();
        titulosacru14 = new javax.swing.JLabel();
        correoinstitucional = new javax.swing.JLabel();
        facultad = new javax.swing.JLabel();
        titulosacru24 = new javax.swing.JLabel();
        titulosacru25 = new javax.swing.JLabel();
        programa = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        titulosacru28 = new javax.swing.JLabel();
        panelsolicitarmatricula = new javax.swing.JPanel();
        botonayuda = new javax.swing.JButton();
        titulosacru5 = new javax.swing.JLabel();
        titulosacru6 = new javax.swing.JLabel();
        nombre_programa = new javax.swing.JLabel();
        botonayuda1 = new javax.swing.JButton();
        derechossacruagregarestudiante1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SACRU.");
        setIconImage(getIconImage());

        paneldeusuario.setBackground(new java.awt.Color(0, 0, 0));
        paneldeusuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        paneldeusuario.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 94, 271, 10));

        nombreusuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreusuario.setText("NOMBRE ESTUDIANTE");
        paneldeusuario.add(nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 23, -1, -1));

        cargousuario.setForeground(new java.awt.Color(255, 255, 255));
        cargousuario.setText("ESTUDIANTE-PREGRADO.");
        paneldeusuario.add(cargousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 48, -1, -1));

        logosacrumenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosacrudef.png"))); // NOI18N
        paneldeusuario.add(logosacrumenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, -1));

        logousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        paneldeusuario.add(logousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        titulosacru4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulosacru4.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru4.setText("SACRU");
        paneldeusuario.add(titulosacru4, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 36, -1, -1));

        menugeneral.setBackground(new java.awt.Color(0, 0, 0));

        titulomenu.setForeground(new java.awt.Color(255, 255, 255));
        titulomenu.setText("MENÚ GENERAL.");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        botoninicio.setText("Inicio.");
        botoninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninicioActionPerformed(evt);
            }
        });

        botoninfoestudiante.setText("Información personal.");
        botoninfoestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninfoestudianteActionPerformed(evt);
            }
        });

        botonmatricula.setText("Matrícula.");
        botonmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menugeneralLayout = new javax.swing.GroupLayout(menugeneral);
        menugeneral.setLayout(menugeneralLayout);
        menugeneralLayout.setHorizontalGroup(
            menugeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(jSeparator6)
            .addComponent(jSeparator5)
            .addComponent(botoninicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoninfoestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menugeneralLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(titulomenu)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        menugeneralLayout.setVerticalGroup(
            menugeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menugeneralLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(titulomenu)
                .addGap(18, 18, 18)
                .addComponent(botoninicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(botoninfoestudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonmatricula)
                .addGap(13, 13, 13)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        panelfondoinicioblanco.setBackground(new java.awt.Color(255, 255, 255));
        panelfondoinicioblanco.setPreferredSize(new java.awt.Dimension(778, 340));

        panelfondoinicioblanco1.setBackground(new java.awt.Color(255, 255, 255));
        panelfondoinicioblanco1.setPreferredSize(new java.awt.Dimension(778, 340));

        derechossacruagregarestudiante.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante.setText("Universidad de los Llanos © Todos los derechos reservados ");

        titulosacru2.setFont(new java.awt.Font("Dialog", 0, 80)); // NOI18N
        titulosacru2.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulosacru2.setText("SACRU");

        titulosacru3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru3.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru3.setText("Sistema Académico y Control de Recursos Unillanos.");

        botoncontacto.setText("Contacto.");
        botoncontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncontactoActionPerformed(evt);
            }
        });

        botoncerrarsesion.setText("Cerrar sesión.");
        botoncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelfondoinicioblanco1Layout = new javax.swing.GroupLayout(panelfondoinicioblanco1);
        panelfondoinicioblanco1.setLayout(panelfondoinicioblanco1Layout);
        panelfondoinicioblanco1Layout.setHorizontalGroup(
            panelfondoinicioblanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoinicioblanco1Layout.createSequentialGroup()
                .addGroup(panelfondoinicioblanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfondoinicioblanco1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(titulosacru2))
                    .addGroup(panelfondoinicioblanco1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(titulosacru3)))
                .addContainerGap(431, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondoinicioblanco1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelfondoinicioblanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondoinicioblanco1Layout.createSequentialGroup()
                        .addComponent(derechossacruagregarestudiante)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondoinicioblanco1Layout.createSequentialGroup()
                        .addGroup(panelfondoinicioblanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botoncontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botoncerrarsesion))
                        .addGap(78, 78, 78))))
        );
        panelfondoinicioblanco1Layout.setVerticalGroup(
            panelfondoinicioblanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoinicioblanco1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(botoncontacto)
                .addGroup(panelfondoinicioblanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfondoinicioblanco1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(titulosacru2))
                    .addGroup(panelfondoinicioblanco1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(botoncerrarsesion)))
                .addGap(8, 8, 8)
                .addComponent(titulosacru3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(derechossacruagregarestudiante)
                .addGap(78, 78, 78))
        );

        panelinfoestudiante.setBackground(new java.awt.Color(255, 255, 255));
        panelinfoestudiante.setPreferredSize(new java.awt.Dimension(778, 340));

        informacionpersonalestudiante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        informacionpersonalestudiante.setText("INFORMACIÓN PERSONAL.");

        botonayuda2.setText("Ayuda.");
        botonayuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonayuda2ActionPerformed(evt);
            }
        });

        derechossacruagregarestudiante2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante2.setText("Universidad de los Llanos © Todos los derechos reservados ");

        nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombre.setText("Nombre completo: ");

        nombrecompleto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombrecompleto.setText("-------------------------");

        tipodocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tipodocumento.setText("-------------------------");

        tipodedocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tipodedocumento.setText("Tipo de documento: ");

        titulosacru12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru12.setText("Número de documento:");

        numerodocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        numerodocumento.setText("-------------------------");

        correopersonal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        correopersonal.setText("-------------------------");

        titulosacru13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru13.setText("Correo personal:");

        titulosacru14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru14.setText("Correo institucional:");

        correoinstitucional.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        correoinstitucional.setText("-------------------------");

        facultad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        facultad.setText("-------------------------");

        titulosacru24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru24.setText("Facultad:");

        titulosacru25.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru25.setText("Programa:");

        programa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        programa.setText("-------------------------");

        estado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estado.setText("-------------------------");

        titulosacru28.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru28.setText("Estado:");

        javax.swing.GroupLayout panelinfoestudianteLayout = new javax.swing.GroupLayout(panelinfoestudiante);
        panelinfoestudiante.setLayout(panelinfoestudianteLayout);
        panelinfoestudianteLayout.setHorizontalGroup(
            panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(nombre)
                        .addGap(12, 12, 12)
                        .addComponent(nombrecompleto))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(tipodedocumento)
                        .addGap(6, 6, 6)
                        .addComponent(tipodocumento))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(titulosacru12)
                        .addGap(6, 6, 6)
                        .addComponent(numerodocumento))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(titulosacru13)
                        .addGap(43, 43, 43)
                        .addComponent(correopersonal))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(titulosacru14)
                        .addGap(6, 6, 6)
                        .addComponent(correoinstitucional))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(titulosacru24)
                        .addGap(39, 39, 39)
                        .addComponent(facultad))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(titulosacru25)
                        .addGap(31, 31, 31)
                        .addComponent(programa))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addComponent(titulosacru28)
                        .addGap(47, 47, 47)
                        .addComponent(estado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfoestudianteLayout.createSequentialGroup()
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(informacionpersonalestudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(botonayuda2))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(derechossacruagregarestudiante2)))
                .addGap(42, 42, 42))
        );
        panelinfoestudianteLayout.setVerticalGroup(
            panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(informacionpersonalestudiante))
                    .addGroup(panelinfoestudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonayuda2)))
                .addGap(21, 21, 21)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(nombrecompleto))
                .addGap(6, 6, 6)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipodedocumento)
                    .addComponent(tipodocumento))
                .addGap(6, 6, 6)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulosacru12)
                    .addComponent(numerodocumento))
                .addGap(6, 6, 6)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulosacru13)
                    .addComponent(correopersonal))
                .addGap(6, 6, 6)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulosacru14)
                    .addComponent(correoinstitucional))
                .addGap(12, 12, 12)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulosacru24)
                    .addComponent(facultad))
                .addGap(6, 6, 6)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulosacru25)
                    .addComponent(programa))
                .addGap(6, 6, 6)
                .addGroup(panelinfoestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulosacru28)
                    .addComponent(estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(derechossacruagregarestudiante2)
                .addGap(44, 44, 44))
        );

        panelsolicitarmatricula.setBackground(new java.awt.Color(255, 255, 255));
        panelsolicitarmatricula.setPreferredSize(new java.awt.Dimension(778, 340));

        botonayuda.setText("Ayuda.");
        botonayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonayudaActionPerformed(evt);
            }
        });

        titulosacru5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulosacru5.setText("SOLICITAR MATRÍCULA.");

        titulosacru6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru6.setText("Programa: ");

        nombre_programa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombre_programa.setText("-------------------------");

        botonayuda1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonayuda1.setText("Descargar recibo.");
        botonayuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonayuda1ActionPerformed(evt);
            }
        });

        derechossacruagregarestudiante1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante1.setText("Universidad de los Llanos © Todos los derechos reservados ");

        javax.swing.GroupLayout panelsolicitarmatriculaLayout = new javax.swing.GroupLayout(panelsolicitarmatricula);
        panelsolicitarmatricula.setLayout(panelsolicitarmatriculaLayout);
        panelsolicitarmatriculaLayout.setHorizontalGroup(
            panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                        .addGroup(panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                                .addGap(206, 206, Short.MAX_VALUE)
                                .addComponent(derechossacruagregarestudiante1))
                            .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonayuda))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelsolicitarmatriculaLayout.createSequentialGroup()
                                .addComponent(titulosacru6)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 203, Short.MAX_VALUE)))
                        .addGap(47, 47, 47))
                    .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                        .addGroup(panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulosacru5)
                            .addComponent(botonayuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelsolicitarmatriculaLayout.setVerticalGroup(
            panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonayuda)
                .addGroup(panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(titulosacru5)
                        .addGap(85, 85, 85)
                        .addComponent(botonayuda1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(derechossacruagregarestudiante1)
                        .addGap(44, 44, 44))
                    .addGroup(panelsolicitarmatriculaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(panelsolicitarmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_programa)
                            .addComponent(titulosacru6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout panelfondoinicioblancoLayout = new javax.swing.GroupLayout(panelfondoinicioblanco);
        panelfondoinicioblanco.setLayout(panelfondoinicioblancoLayout);
        panelfondoinicioblancoLayout.setHorizontalGroup(
            panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
            .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelfondoinicioblanco1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(panelinfoestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
            .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(panelsolicitarmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelfondoinicioblancoLayout.setVerticalGroup(
            panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelfondoinicioblanco1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(panelinfoestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelsolicitarmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menugeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneldeusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelfondoinicioblanco, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(menugeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(paneldeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelfondoinicioblanco, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerrarsesionActionPerformed
        LOGIN c = new LOGIN();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoncerrarsesionActionPerformed

    public String ruta_archivo() {
        JFileChooser dlg = new JFileChooser();
        int opcion = dlg.showSaveDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            String ruta = f.toString();
            return ruta;

        }
        return null;
    }
    private void botonayuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonayuda1ActionPerformed
        
        generarpdf g = new generarpdf();
        Liquidacionderecibo liq = new Liquidacionderecibo();
        Estudiante est = recibir_usuario(usuario_online);
        boolean descarga = liq.validar_recibo(est.getNumero_documento(), objconexion);
        if (descarga) {
            String ruta = ruta_archivo();
            String titulo = "UNIVERSIDAD DE LOS LLANOS \n "
                    + "TALENTO Y CONOCIMIENTO PARA EL DESARROLLO REGIONAL ";

            String cuerpo = liq.informacion_recibo_pdf(est.getNumero_documento(), objconexion);

            g.generarPDF(titulo, cuerpo, "Universidad de los Llanos © Todos los derechos reservados ", "C:\\Users\\ADMIN\\Pictures\\unillanos.png", ruta);
            JOptionPane.showMessageDialog(null, "recibo de liquidacion descargado");

        } else {
            JOptionPane.showMessageDialog(null, "no puedes descargar tu matricula");

        }


    }//GEN-LAST:event_botonayuda1ActionPerformed

    private void botoninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninicioActionPerformed
        panelsolicitarmatricula.setVisible(false);
        panelinfoestudiante.setVisible(false);
        panelfondoinicioblanco1.setVisible(true);
        panelfondoinicioblanco.setVisible(true);
    }//GEN-LAST:event_botoninicioActionPerformed

    private void botoninfoestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninfoestudianteActionPerformed
        panelfondoinicioblanco1.setVisible(false);
        panelfondoinicioblanco.setVisible(true);
        panelsolicitarmatricula.setVisible(false);
        panelinfoestudiante.setVisible(true);
    }//GEN-LAST:event_botoninfoestudianteActionPerformed

    private void botonmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmatriculaActionPerformed
        panelfondoinicioblanco1.setVisible(false);
        panelfondoinicioblanco.setVisible(true);
        panelinfoestudiante.setVisible(false);
        panelsolicitarmatricula.setVisible(true);
    }//GEN-LAST:event_botonmatriculaActionPerformed

    private void botoncontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncontactoActionPerformed
        JOptionPane.showMessageDialog(null, "Correo: sacru@unillanos.edu.co");
    }//GEN-LAST:event_botoncontactoActionPerformed

    private void botonayuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonayuda2ActionPerformed
        JOptionPane.showMessageDialog(null, "Correo sacru@unillanos.edu.co");
    }//GEN-LAST:event_botonayuda2ActionPerformed

    private void botonayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonayudaActionPerformed
        JOptionPane.showMessageDialog(null, "Correo sacru@unillanos.edu.co");
    }//GEN-LAST:event_botonayudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIOESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIOESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIOESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIOESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new INICIOESTUDIANTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonayuda;
    private javax.swing.JButton botonayuda1;
    private javax.swing.JButton botonayuda2;
    private javax.swing.JButton botoncerrarsesion;
    private javax.swing.JButton botoncontacto;
    private javax.swing.JButton botoninfoestudiante;
    private javax.swing.JButton botoninicio;
    private javax.swing.JButton botonmatricula;
    private javax.swing.JLabel cargousuario;
    private javax.swing.JLabel correoinstitucional;
    private javax.swing.JLabel correopersonal;
    private javax.swing.JLabel derechossacruagregarestudiante;
    private javax.swing.JLabel derechossacruagregarestudiante1;
    private javax.swing.JLabel derechossacruagregarestudiante2;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel facultad;
    private javax.swing.JLabel informacionpersonalestudiante;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logosacrumenu;
    private javax.swing.JLabel logousuario;
    private javax.swing.JPanel menugeneral;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre_programa;
    private javax.swing.JLabel nombrecompleto;
    private javax.swing.JLabel nombreusuario;
    private javax.swing.JLabel numerodocumento;
    private javax.swing.JPanel paneldeusuario;
    private javax.swing.JPanel panelfondoinicioblanco;
    private javax.swing.JPanel panelfondoinicioblanco1;
    private javax.swing.JPanel panelinfoestudiante;
    private javax.swing.JPanel panelsolicitarmatricula;
    private javax.swing.JLabel programa;
    private javax.swing.JLabel tipodedocumento;
    private javax.swing.JLabel tipodocumento;
    private javax.swing.JLabel titulomenu;
    private javax.swing.JLabel titulosacru12;
    private javax.swing.JLabel titulosacru13;
    private javax.swing.JLabel titulosacru14;
    private javax.swing.JLabel titulosacru2;
    private javax.swing.JLabel titulosacru24;
    private javax.swing.JLabel titulosacru25;
    private javax.swing.JLabel titulosacru28;
    private javax.swing.JLabel titulosacru3;
    private javax.swing.JLabel titulosacru4;
    private javax.swing.JLabel titulosacru5;
    private javax.swing.JLabel titulosacru6;
    // End of variables declaration//GEN-END:variables
}
