package ventanas;

import Clases.Administrador;
import Clases.Estudiante;
import Clases.Facultad;
import Clases.Liquidacionderecibo;
import Clases.Login;
import Clases.Programa;
import conexion.conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static ventanas.INICIOESTUDIANTE.usuario_online;

/**
 */
public class inicioadministrador1 extends javax.swing.JFrame {

    conexion objconexion = new conexion();

    public static String usuario_online = "";
    /**
     * Creates new form inicioadministrador
     */

    Programa programas = new Programa();
    Facultad facultad = new Facultad();

    public inicioadministrador1() {
        initComponents();
        LOGIN objLOGIN = new LOGIN();
        //pasar el usuario online de LOGIN
        nombreusuario.setText(objLOGIN.usuario_online);
        usuario_online = nombreusuario.getText();
        objconexion.conexiones();
        recibir_usuario(usuario_online);
        programas.listar_programas(campoprograma1, objconexion);
        programas.listar_programas(buscarporprogramas1, objconexion);
        facultad.listar_facultad(buscarporfacultades1, objconexion);
        //para que el usuario no edite la edad en el spinner
        ((JSpinner.DefaultEditor) edad_estudiante1.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) periodo_ingreso1.getEditor()).getTextField().setEditable(false);
        //para que los combobox no se puedan editar
        camposexo2.setEditable(false);
        campoprograma1.setEditable(false);
        campotipodedocumento2.setEditable(false);

        panelfondoinicioblanco.setVisible(true);

        panelmatricula.setVisible(false);
        panelinicioregistro1.setVisible(false);
        panelinfoadmin.setVisible(false);
        //  panelbuscarestudiantes.setVisible(false);
        panelresultadoestudiantes.setVisible(false);
        ///PARA CENTRAR LA VENTANA
        this.setLocationRelativeTo(null);
        ///PARA QUITAR EL MAXIMAR DE LA VENTANA
        this.setResizable(false);

    }

    ////PARA CAMBIAR EL ICONO DE LA VENTANA
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logosacru2.png"));

        return retValue;
    }

    public Administrador recibir_usuario(String usuario) {
        Login objlogin = new Login();

        Administrador objadmin = objlogin.obtener_info_administrador(usuario, objconexion);
        nombreusuario.setText(objadmin.getNombre_1() + " " + objadmin.getNombre_2() + " " + objadmin.getApellido_1() + " " + objadmin.getApellido_2());
        camponombreadmin.setText(objadmin.getNombre_1() + " " + objadmin.getNombre_2() + " " + objadmin.getApellido_1() + " " + objadmin.getApellido_2());
        campotipodedocumento.setText(objadmin.getTipo_documento());
        camponumerodedocumento.setText(objadmin.getNumero_documento());
        campocorreopersonal.setText(objadmin.getCorreo_personal());
        campocorreoinstitucional.setText(objadmin.getCorreo_institucional());
        // String numCadena= Integer.toString(numEntero);
        String edad = Integer.toString(objadmin.getEdad());
        String numero_celular = Long.toString(objadmin.getNumero_celular());
        String codigo = Integer.toString(objadmin.getCodigo());
        campoedad.setText(edad);
        camposexo.setText(objadmin.getSexo());
        campocargo.setText(objadmin.getCargo());
        camponumerodecelular.setText(numero_celular);
        campocodigo.setText(codigo);

        return objadmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menugeneral = new javax.swing.JPanel();
        titulomenu = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        botoninicio = new javax.swing.JButton();
        botoninfoadmin = new javax.swing.JButton();
        botonregistroestudiante = new javax.swing.JButton();
        botongenerarmatriculaadmin = new javax.swing.JButton();
        botonvisualizarestudiantes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        paneldeusuario = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        titulosacru2 = new javax.swing.JLabel();
        nombreusuario = new javax.swing.JLabel();
        cargousuario = new javax.swing.JLabel();
        logosacrumenu = new javax.swing.JLabel();
        logousuario = new javax.swing.JLabel();
        panelderechoblanco = new javax.swing.JPanel();
        panelfondoinicioblanco = new javax.swing.JPanel();
        titulosacru3 = new javax.swing.JLabel();
        titulosacru4 = new javax.swing.JLabel();
        botoncontacto1 = new javax.swing.JButton();
        botoncerrarsesion = new javax.swing.JButton();
        derechossacruagregarestudiante3 = new javax.swing.JLabel();
        panelinfoadmin = new javax.swing.JPanel();
        informacionpersonal = new javax.swing.JLabel();
        derechossacruagregarestudiante2 = new javax.swing.JLabel();
        nombreadmin = new javax.swing.JLabel();
        camponombreadmin = new javax.swing.JLabel();
        campotipodedocumento = new javax.swing.JLabel();
        tipodedocumento = new javax.swing.JLabel();
        numerodedocumento = new javax.swing.JLabel();
        camponumerodedocumento = new javax.swing.JLabel();
        campocorreopersonal = new javax.swing.JLabel();
        correopersonal = new javax.swing.JLabel();
        correoinstitucional = new javax.swing.JLabel();
        campocorreoinstitucional = new javax.swing.JLabel();
        campoedad = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        camposexo = new javax.swing.JLabel();
        campocargo = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        numcelularadmin = new javax.swing.JLabel();
        camponumerodecelular = new javax.swing.JLabel();
        codigoadmin = new javax.swing.JLabel();
        campocodigo = new javax.swing.JLabel();
        panelmatricula = new javax.swing.JPanel();
        derechosutexto2 = new javax.swing.JLabel();
        titulogenerarmatricula = new javax.swing.JLabel();
        generar_matricula = new javax.swing.JButton();
        botonayuda1 = new javax.swing.JButton();
        botonyear = new com.toedter.calendar.JYearChooser();
        botonperiodoacademico = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelresultadoestudiantes = new javax.swing.JPanel();
        botonayuda3 = new javax.swing.JButton();
        tituloresultadoestudiantes = new javax.swing.JLabel();
        Scrollpanedetabla = new javax.swing.JScrollPane();
        tablaestudiantes = new javax.swing.JTable();
        buscarporprogramas1 = new javax.swing.JComboBox<>();
        buscarporfacultades1 = new javax.swing.JComboBox<>();
        botonconsultar1 = new javax.swing.JButton();
        buscarporcodigos1 = new javax.swing.JTextField();
        campocodigo1 = new javax.swing.JLabel();
        derechossacruagregarestudiante4 = new javax.swing.JLabel();
        panelinicioregistro1 = new javax.swing.JPanel();
        agregarestudiantes1 = new javax.swing.JLabel();
        camponombre2 = new javax.swing.JTextField();
        primernombre1 = new javax.swing.JLabel();
        segundonombre1 = new javax.swing.JLabel();
        camposegundonombre1 = new javax.swing.JTextField();
        primerapellido1 = new javax.swing.JLabel();
        campoprimerapellido1 = new javax.swing.JTextField();
        segundoapellido1 = new javax.swing.JLabel();
        camposegundoapellido1 = new javax.swing.JTextField();
        numerodedocumento2 = new javax.swing.JLabel();
        camponumerodedocumento2 = new javax.swing.JTextField();
        tipodedocumento2 = new javax.swing.JLabel();
        campotipodedocumento2 = new javax.swing.JComboBox<>();
        edad2 = new javax.swing.JLabel();
        sexo2 = new javax.swing.JLabel();
        camposexo2 = new javax.swing.JComboBox<>();
        programa1 = new javax.swing.JLabel();
        campoprograma1 = new javax.swing.JComboBox<>();
        correopersonal2 = new javax.swing.JLabel();
        campocorreopersonal2 = new javax.swing.JTextField();
        botoncancelar1 = new javax.swing.JButton();
        botonguardar1 = new javax.swing.JButton();
        label_codigo_est1 = new javax.swing.JLabel();
        codigo_estudiante1 = new javax.swing.JTextField();
        label_estado1 = new javax.swing.JLabel();
        estado1 = new javax.swing.JTextField();
        label_fecha_in1 = new javax.swing.JLabel();
        label_periodo_in1 = new javax.swing.JLabel();
        periodo_ingreso1 = new javax.swing.JSpinner();
        edad_estudiante1 = new javax.swing.JSpinner();
        derechossacruagregarestudiante1 = new javax.swing.JLabel();
        botonayuda6 = new javax.swing.JButton();
        fecha1 = new com.toedter.calendar.JDateChooser();
        avisonombre = new javax.swing.JLabel();
        avisoprimerapellido = new javax.swing.JLabel();
        avisosegundoapellido = new javax.swing.JLabel();
        avisonumerodocumento = new javax.swing.JLabel();
        avisoestado = new javax.swing.JLabel();
        avisocorreopersonal1 = new javax.swing.JLabel();
        avisocodigoestudiantil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SACRU.");
        setIconImage(getIconImage());

        menugeneral.setBackground(new java.awt.Color(0, 0, 0));

        titulomenu.setForeground(new java.awt.Color(255, 255, 255));
        titulomenu.setText("MENÚ GENERAL.");

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        botoninicio.setText("Inicio.");
        botoninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninicioActionPerformed(evt);
            }
        });

        botoninfoadmin.setText("Información personal.");
        botoninfoadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninfoadminActionPerformed(evt);
            }
        });

        botonregistroestudiante.setText("Registro de usuarios.");
        botonregistroestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregistroestudianteActionPerformed(evt);
            }
        });

        botongenerarmatriculaadmin.setText("Generar matrícula.");
        botongenerarmatriculaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botongenerarmatriculaadminActionPerformed(evt);
            }
        });

        botonvisualizarestudiantes.setText("Visualización estudiantes.");
        botonvisualizarestudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvisualizarestudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menugeneralLayout = new javax.swing.GroupLayout(menugeneral);
        menugeneral.setLayout(menugeneralLayout);
        menugeneralLayout.setHorizontalGroup(
            menugeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menugeneralLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(titulomenu)
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator1)
            .addComponent(botoninicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botoninfoadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonregistroestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botongenerarmatriculaadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonvisualizarestudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );
        menugeneralLayout.setVerticalGroup(
            menugeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menugeneralLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(titulomenu)
                .addGap(18, 18, 18)
                .addComponent(botoninicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(botoninfoadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(botonregistroestudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botongenerarmatriculaadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(botonvisualizarestudiantes)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        paneldeusuario.setBackground(new java.awt.Color(0, 0, 0));
        paneldeusuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        paneldeusuario.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 94, 271, 10));

        titulosacru2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulosacru2.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru2.setText("SACRU");
        paneldeusuario.add(titulosacru2, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 36, -1, -1));

        nombreusuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreusuario.setText("NOMBRE ADMINISTRADOR.");
        paneldeusuario.add(nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 23, -1, -1));

        cargousuario.setForeground(new java.awt.Color(255, 255, 255));
        cargousuario.setText("ADMINISTRADOR.");
        paneldeusuario.add(cargousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 48, -1, -1));

        logosacrumenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosacrudef.png"))); // NOI18N
        paneldeusuario.add(logosacrumenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        logousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        paneldeusuario.add(logousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        panelderechoblanco.setBackground(new java.awt.Color(255, 255, 255));
        panelderechoblanco.setPreferredSize(new java.awt.Dimension(778, 340));

        panelfondoinicioblanco.setBackground(new java.awt.Color(255, 255, 255));
        panelfondoinicioblanco.setPreferredSize(new java.awt.Dimension(778, 340));

        titulosacru3.setFont(new java.awt.Font("Dialog", 0, 80)); // NOI18N
        titulosacru3.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulosacru3.setText("SACRU");

        titulosacru4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        titulosacru4.setForeground(new java.awt.Color(255, 0, 0));
        titulosacru4.setText("Sistema Académico y Control de Recursos Unillanos.");

        botoncontacto1.setText("Contacto.");
        botoncontacto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncontacto1ActionPerformed(evt);
            }
        });

        botoncerrarsesion.setText("Cerrar sesión.");
        botoncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncerrarsesionActionPerformed(evt);
            }
        });

        derechossacruagregarestudiante3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante3.setText("Universidad de los Llanos © Todos los derechos reservados ");

        javax.swing.GroupLayout panelfondoinicioblancoLayout = new javax.swing.GroupLayout(panelfondoinicioblanco);
        panelfondoinicioblanco.setLayout(panelfondoinicioblancoLayout);
        panelfondoinicioblancoLayout.setHorizontalGroup(
            panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondoinicioblancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(derechossacruagregarestudiante3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondoinicioblancoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(titulosacru4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(titulosacru3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoncerrarsesion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botoncontacto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        panelfondoinicioblancoLayout.setVerticalGroup(
            panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                .addGroup(panelfondoinicioblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(titulosacru3))
                    .addGroup(panelfondoinicioblancoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botoncontacto1)
                        .addGap(18, 18, 18)
                        .addComponent(botoncerrarsesion)))
                .addGap(8, 8, 8)
                .addComponent(titulosacru4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(derechossacruagregarestudiante3)
                .addContainerGap())
        );

        panelinfoadmin.setBackground(new java.awt.Color(255, 255, 255));
        panelinfoadmin.setPreferredSize(new java.awt.Dimension(778, 340));

        informacionpersonal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        informacionpersonal.setText("INFORMACIÓN PERSONAL.");

        derechossacruagregarestudiante2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante2.setText("Universidad de los Llanos © Todos los derechos reservados ");

        nombreadmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombreadmin.setText("Nombre completo: ");

        camponombreadmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        camponombreadmin.setText("-------------------------");

        campotipodedocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campotipodedocumento.setText("-------------------------");

        tipodedocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tipodedocumento.setText("Tipo de documento: ");

        numerodedocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        numerodedocumento.setText("Número de documento:");

        camponumerodedocumento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        camponumerodedocumento.setText("-------------------------");

        campocorreopersonal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campocorreopersonal.setText("-------------------------");

        correopersonal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        correopersonal.setText("Correo personal:");

        correoinstitucional.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        correoinstitucional.setText("Correo institucional:");

        campocorreoinstitucional.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campocorreoinstitucional.setText("-------------------------");

        campoedad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoedad.setText("-------------------------");

        edad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        edad.setText("Edad:");

        sexo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        sexo.setText("Sexo:");

        camposexo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        camposexo.setText("-------------------------");

        campocargo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campocargo.setText("-------------------------");

        cargo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cargo.setText("Cargo:");

        numcelularadmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        numcelularadmin.setText("Número de celular: ");

        camponumerodecelular.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        camponumerodecelular.setText("-------------------------");

        codigoadmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigoadmin.setText("Código: ");

        campocodigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campocodigo.setText("-------------------------");

        javax.swing.GroupLayout panelinfoadminLayout = new javax.swing.GroupLayout(panelinfoadmin);
        panelinfoadmin.setLayout(panelinfoadminLayout);
        panelinfoadminLayout.setHorizontalGroup(
            panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoadminLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(nombreadmin)
                        .addGap(12, 12, 12)
                        .addComponent(camponombreadmin))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(tipodedocumento)
                        .addGap(6, 6, 6)
                        .addComponent(campotipodedocumento))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(numerodedocumento)
                        .addGap(6, 6, 6)
                        .addComponent(camponumerodedocumento))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(correopersonal)
                        .addGap(43, 43, 43)
                        .addComponent(campocorreopersonal))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(correoinstitucional)
                        .addGap(6, 6, 6)
                        .addComponent(campocorreoinstitucional))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(edad)
                        .addGap(39, 39, 39)
                        .addComponent(campoedad))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(codigoadmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campocodigo))
                    .addGroup(panelinfoadminLayout.createSequentialGroup()
                        .addComponent(numcelularadmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(camponumerodecelular))
                    .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelinfoadminLayout.createSequentialGroup()
                            .addComponent(cargo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campocargo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelinfoadminLayout.createSequentialGroup()
                            .addComponent(sexo)
                            .addGap(31, 31, 31)
                            .addComponent(camposexo))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelinfoadminLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(informacionpersonal)
                .addGap(24, 268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfoadminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(derechossacruagregarestudiante2)
                .addGap(32, 32, 32))
        );
        panelinfoadminLayout.setVerticalGroup(
            panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoadminLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(informacionpersonal)
                .addGap(21, 21, 21)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreadmin)
                    .addComponent(camponombreadmin))
                .addGap(6, 6, 6)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipodedocumento)
                    .addComponent(campotipodedocumento))
                .addGap(6, 6, 6)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numerodedocumento)
                    .addComponent(camponumerodedocumento))
                .addGap(6, 6, 6)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correopersonal)
                    .addComponent(campocorreopersonal))
                .addGap(6, 6, 6)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correoinstitucional)
                    .addComponent(campocorreoinstitucional))
                .addGap(12, 12, 12)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edad)
                    .addComponent(campoedad))
                .addGap(6, 6, 6)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexo)
                    .addComponent(camposexo))
                .addGap(6, 6, 6)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargo)
                    .addComponent(campocargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numcelularadmin)
                    .addComponent(camponumerodecelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelinfoadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoadmin)
                    .addComponent(campocodigo))
                .addGap(33, 33, 33)
                .addComponent(derechossacruagregarestudiante2))
        );

        panelmatricula.setBackground(new java.awt.Color(255, 255, 255));
        panelmatricula.setPreferredSize(new java.awt.Dimension(778, 340));

        derechosutexto2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechosutexto2.setText("Universidad de los Llanos © Todos los derechos reservados ");

        titulogenerarmatricula.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulogenerarmatricula.setText("GENERAR MATRÍCULA.");

        generar_matricula.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        generar_matricula.setText("Generar matrícula.");
        generar_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_matriculaActionPerformed(evt);
            }
        });

        botonayuda1.setText("Ayuda.");
        botonayuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonayuda1ActionPerformed(evt);
            }
        });

        botonperiodoacademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Año");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Periodo");

        javax.swing.GroupLayout panelmatriculaLayout = new javax.swing.GroupLayout(panelmatricula);
        panelmatricula.setLayout(panelmatriculaLayout);
        panelmatriculaLayout.setHorizontalGroup(
            panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmatriculaLayout.createSequentialGroup()
                .addGroup(panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmatriculaLayout.createSequentialGroup()
                        .addGroup(panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelmatriculaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(titulogenerarmatricula)
                                .addGap(209, 209, 209))
                            .addGroup(panelmatriculaLayout.createSequentialGroup()
                                .addContainerGap(272, Short.MAX_VALUE)
                                .addGroup(panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generar_matricula)
                                    .addGroup(panelmatriculaLayout.createSequentialGroup()
                                        .addComponent(botonyear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(botonperiodoacademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelmatriculaLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel2)))
                                .addGap(196, 196, 196)))
                        .addComponent(botonayuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmatriculaLayout.createSequentialGroup()
                        .addContainerGap(479, Short.MAX_VALUE)
                        .addComponent(derechosutexto2)))
                .addContainerGap())
        );
        panelmatriculaLayout.setVerticalGroup(
            panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmatriculaLayout.createSequentialGroup()
                .addGroup(panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmatriculaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonayuda1))
                    .addGroup(panelmatriculaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(titulogenerarmatricula)))
                .addGap(35, 35, 35)
                .addGroup(panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(panelmatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonperiodoacademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(generar_matricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(derechosutexto2))
        );

        panelresultadoestudiantes.setBackground(new java.awt.Color(255, 255, 255));

        botonayuda3.setText("Ayuda.");
        botonayuda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonayuda3ActionPerformed(evt);
            }
        });

        tituloresultadoestudiantes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tituloresultadoestudiantes.setText("ESTUDIANTES");

        tablaestudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre.", "Código.", "Tipo de documento.", "Documento.", "Programa.", "Facultad.", "Estado.", "Correo personal.", "Correo institucional."
            }
        ));
        Scrollpanedetabla.setViewportView(tablaestudiantes);

        buscarporprogramas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarporprogramas1ActionPerformed(evt);
            }
        });

        buscarporfacultades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarporfacultades1ActionPerformed(evt);
            }
        });

        botonconsultar1.setText("Consultar.");
        botonconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultar1ActionPerformed(evt);
            }
        });

        campocodigo1.setText("Código:");

        derechossacruagregarestudiante4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante4.setText("Universidad de los Llanos © Todos los derechos reservados ");

        javax.swing.GroupLayout panelresultadoestudiantesLayout = new javax.swing.GroupLayout(panelresultadoestudiantes);
        panelresultadoestudiantes.setLayout(panelresultadoestudiantesLayout);
        panelresultadoestudiantesLayout.setHorizontalGroup(
            panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelresultadoestudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelresultadoestudiantesLayout.createSequentialGroup()
                        .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelresultadoestudiantesLayout.createSequentialGroup()
                                .addComponent(buscarporprogramas1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(buscarporfacultades1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campocodigo1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelresultadoestudiantesLayout.createSequentialGroup()
                        .addComponent(buscarporcodigos1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(botonconsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelresultadoestudiantesLayout.createSequentialGroup()
                .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelresultadoestudiantesLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(tituloresultadoestudiantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonayuda3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelresultadoestudiantesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(derechossacruagregarestudiante4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Scrollpanedetabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelresultadoestudiantesLayout.setVerticalGroup(
            panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelresultadoestudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloresultadoestudiantes)
                    .addComponent(botonayuda3))
                .addGap(17, 17, 17)
                .addComponent(campocodigo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonconsultar1)
                    .addComponent(buscarporcodigos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelresultadoestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarporprogramas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarporfacultades1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Scrollpanedetabla, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derechossacruagregarestudiante4))
        );

        panelinicioregistro1.setBackground(new java.awt.Color(255, 255, 255));
        panelinicioregistro1.setPreferredSize(new java.awt.Dimension(778, 340));

        agregarestudiantes1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        agregarestudiantes1.setText("AGREGAR ESTUDIANTES.");

        camponombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                camponombre2KeyTyped(evt);
            }
        });

        primernombre1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        primernombre1.setText("Primer nombre:");

        segundonombre1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        segundonombre1.setText("Segundo nombre: ");

        camposegundonombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                camposegundonombre1KeyTyped(evt);
            }
        });

        primerapellido1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        primerapellido1.setText("Primer Apellido: ");

        campoprimerapellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoprimerapellido1KeyTyped(evt);
            }
        });

        segundoapellido1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        segundoapellido1.setText("Segundo Apellido:");

        camposegundoapellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                camposegundoapellido1KeyTyped(evt);
            }
        });

        numerodedocumento2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        numerodedocumento2.setText("Número de documento: ");

        camponumerodedocumento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                camponumerodedocumento2KeyTyped(evt);
            }
        });

        tipodedocumento2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tipodedocumento2.setText("Tipo de documento: ");

        campotipodedocumento2.setEditable(true);
        campotipodedocumento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "T.I" }));

        edad2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edad2.setText("Edad: ");

        sexo2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sexo2.setText("Sexo: ");

        camposexo2.setEditable(true);
        camposexo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "h" }));
        camposexo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                camposexo2ItemStateChanged(evt);
            }
        });

        programa1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        programa1.setText("Programa: ");

        campoprograma1.setEditable(true);

        correopersonal2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        correopersonal2.setText("Correo personal: ");

        campocorreopersonal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campocorreopersonal2KeyTyped(evt);
            }
        });

        botoncancelar1.setText("Cancelar.");
        botoncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelar1ActionPerformed(evt);
            }
        });

        botonguardar1.setText("Guardar.");
        botonguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardar1ActionPerformed(evt);
            }
        });

        label_codigo_est1.setText("Código estudiantil:");

        codigo_estudiante1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_estudiante1KeyTyped(evt);
            }
        });

        label_estado1.setText("Estado:");

        estado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado1ActionPerformed(evt);
            }
        });
        estado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estado1KeyTyped(evt);
            }
        });

        label_fecha_in1.setText("Fecha de ingreso:");

        label_periodo_in1.setText("Periodo de ingreso:");

        periodo_ingreso1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));

        edad_estudiante1.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));

        derechossacruagregarestudiante1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        derechossacruagregarestudiante1.setText("Universidad de los Llanos © Todos los derechos reservados ");

        botonayuda6.setText("Ayuda.");
        botonayuda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonayuda6ActionPerformed(evt);
            }
        });

        fecha1.setDateFormatString("dd/MM/yyyy");

        avisonombre.setForeground(new java.awt.Color(255, 0, 0));

        avisoprimerapellido.setForeground(new java.awt.Color(255, 0, 0));

        avisosegundoapellido.setForeground(new java.awt.Color(255, 0, 0));

        avisonumerodocumento.setForeground(new java.awt.Color(255, 0, 0));

        avisoestado.setForeground(new java.awt.Color(255, 0, 0));

        avisocorreopersonal1.setForeground(new java.awt.Color(255, 0, 0));

        avisocodigoestudiantil.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelinicioregistro1Layout = new javax.swing.GroupLayout(panelinicioregistro1);
        panelinicioregistro1.setLayout(panelinicioregistro1Layout);
        panelinicioregistro1Layout.setHorizontalGroup(
            panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                .addComponent(numerodedocumento2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(camponumerodedocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelinicioregistro1Layout.createSequentialGroup()
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(segundoapellido1)
                                    .addComponent(primernombre1)
                                    .addComponent(segundonombre1)
                                    .addComponent(primerapellido1))
                                .addGap(39, 39, 39)
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(camposegundoapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoprimerapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(camposegundonombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(camponombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(agregarestudiantes1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipodedocumento2)
                                    .addComponent(sexo2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edad2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campotipodedocumento2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(edad_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(camposexo2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinicioregistro1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonayuda6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(avisonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(avisoprimerapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(avisosegundoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(avisonumerodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addComponent(botoncancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label_fecha_in1)
                                    .addComponent(label_periodo_in1)
                                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelinicioregistro1Layout.createSequentialGroup()
                                                    .addComponent(programa1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(campoprograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                                    .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(correopersonal2)
                                                        .addComponent(label_estado1))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(campocorreopersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(codigo_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(periodo_ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonguardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(label_codigo_est1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(avisocorreopersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(avisoestado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(avisocodigoestudiantil, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 6, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinicioregistro1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(derechossacruagregarestudiante1)))
                .addContainerGap())
        );
        panelinicioregistro1Layout.setVerticalGroup(
            panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarestudiantes1)
                    .addComponent(botonayuda6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(primernombre1)
                            .addComponent(camponombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avisonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(camposegundonombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segundonombre1))
                        .addGap(7, 7, 7)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(campoprimerapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(primerapellido1))
                                            .addComponent(avisoprimerapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(segundoapellido1)
                                            .addComponent(camposegundoapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(avisosegundoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(camponumerodedocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numerodedocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(avisonumerodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campotipodedocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipodedocumento2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(camposexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edad_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad2))
                        .addGap(55, 55, 55))
                    .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoprograma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programa1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campocorreopersonal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(correopersonal2))
                            .addComponent(avisocorreopersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_codigo_est1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelinicioregistro1Layout.createSequentialGroup()
                                .addComponent(avisoestado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(avisocodigoestudiantil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_fecha_in1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(periodo_ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_periodo_in1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelinicioregistro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonguardar1)
                            .addComponent(botoncancelar1))
                        .addGap(18, 18, 18)
                        .addComponent(derechossacruagregarestudiante1))))
        );

        javax.swing.GroupLayout panelderechoblancoLayout = new javax.swing.GroupLayout(panelderechoblanco);
        panelderechoblanco.setLayout(panelderechoblancoLayout);
        panelderechoblancoLayout.setHorizontalGroup(
            panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelderechoblancoLayout.createSequentialGroup()
                .addComponent(panelfondoinicioblanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelinfoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(panelresultadoestudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelinicioregistro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelderechoblancoLayout.setVerticalGroup(
            panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondoinicioblanco, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelinfoadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelresultadoestudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelderechoblancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelderechoblancoLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(panelinicioregistro1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menugeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneldeusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelderechoblanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menugeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneldeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelderechoblanco, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninicioActionPerformed
        panelderechoblanco.setVisible(true);
        panelfondoinicioblanco.setVisible(true);

        panelmatricula.setVisible(false);
        panelinicioregistro1.setVisible(false);
        // panelbuscarestudiantes.setVisible(false);
        panelresultadoestudiantes.setVisible(false);
        //  panelinfoadmin.setVisible(false);
    }//GEN-LAST:event_botoninicioActionPerformed

    private void botoninfoadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninfoadminActionPerformed
        panelderechoblanco.setVisible(true);
        panelfondoinicioblanco.setVisible(false);

        panelmatricula.setVisible(false);
        panelinicioregistro1.setVisible(false);
        panelinfoadmin.setVisible(true);
        //   panelbuscarestudiantes.setVisible(false);
        panelresultadoestudiantes.setVisible(false);
    }//GEN-LAST:event_botoninfoadminActionPerformed

    private void botonregistroestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregistroestudianteActionPerformed
        panelderechoblanco.setVisible(true);
        panelfondoinicioblanco.setVisible(false);

        panelmatricula.setVisible(false);
        panelinicioregistro1.setVisible(true);
        panelinfoadmin.setVisible(false);
        //panelbuscarestudiantes.setVisible(false);
        panelresultadoestudiantes.setVisible(false);
    }//GEN-LAST:event_botonregistroestudianteActionPerformed

    private void botongenerarmatriculaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botongenerarmatriculaadminActionPerformed
        panelderechoblanco.setVisible(true);
        panelfondoinicioblanco.setVisible(false);

        panelmatricula.setVisible(true);
        panelinicioregistro1.setVisible(false);
        //  panelbuscarestudiantes.setVisible(false);
        panelresultadoestudiantes.setVisible(false);
        //  panelinfoadmin.setVisible(false);
    }//GEN-LAST:event_botongenerarmatriculaadminActionPerformed

    private void botoncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncerrarsesionActionPerformed
        LOGIN c = new LOGIN();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botoncerrarsesionActionPerformed

    private void generar_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_matriculaActionPerformed
        Liquidacionderecibo obj = new Liquidacionderecibo();
        int año = botonyear.getYear();
        int periodo = Integer.parseInt(botonperiodoacademico.getSelectedItem().toString());
        obj.generar_liquidacion(objconexion, año, periodo);
        JOptionPane.showMessageDialog(null, "Matrículas generadas.");
    }//GEN-LAST:event_generar_matriculaActionPerformed

    private void botonvisualizarestudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvisualizarestudiantesActionPerformed
        panelderechoblanco.setVisible(true);
        panelfondoinicioblanco.setVisible(false);

        panelmatricula.setVisible(false);
        panelinicioregistro1.setVisible(false);
        panelinfoadmin.setVisible(false);

        panelresultadoestudiantes.setVisible(true);
    }//GEN-LAST:event_botonvisualizarestudiantesActionPerformed

    /* void LimpiarJTable(DefaultTableModel modelo ){
   int a =modelo.getRowCount()-1;
   for(int i=0; i<a;i++){
      modelo.removeRow(i );
   }
}*/
    public void limpiarTabla(JTable tabla, DefaultTableModel modelo) {
        try {
            int filas = tabla.getRowCount();
            for (int i = 0; i < filas; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void buscarporprogramas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarporprogramas1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaestudiantes.getModel();
        limpiarTabla(tablaestudiantes, modelo);
        Programa objprograma = new Programa();

        String programa = buscarporprogramas1.getSelectedItem().toString();
        objprograma.listar_por_programa(tablaestudiantes, programa, objconexion);
    }//GEN-LAST:event_buscarporprogramas1ActionPerformed

    private void buscarporfacultades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarporfacultades1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaestudiantes.getModel();
        limpiarTabla(tablaestudiantes, modelo);
        Facultad objfacultad = new Facultad();

        String facultad = buscarporfacultades1.getSelectedItem().toString();
        objfacultad.listar_por_facultad(tablaestudiantes, facultad, objconexion);
    }//GEN-LAST:event_buscarporfacultades1ActionPerformed

    private void botonconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultar1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaestudiantes.getModel();
        limpiarTabla(tablaestudiantes, modelo);

        Estudiante est = new Estudiante();
        int codigo = Integer.parseInt(buscarporcodigos1.getText());
        est.listar_por_codigo(tablaestudiantes, codigo, objconexion);


    }//GEN-LAST:event_botonconsultar1ActionPerformed

    private void camponombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camponombre2KeyTyped
        validacionCaracteres(evt);
    }//GEN-LAST:event_camponombre2KeyTyped

    private void camposegundonombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camposegundonombre1KeyTyped
        validacionCaracteres(evt);
    }//GEN-LAST:event_camposegundonombre1KeyTyped

    private void campoprimerapellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoprimerapellido1KeyTyped
        validacionCaracteres(evt);
    }//GEN-LAST:event_campoprimerapellido1KeyTyped

    private void camposegundoapellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camposegundoapellido1KeyTyped
        validacionCaracteres(evt);
    }//GEN-LAST:event_camposegundoapellido1KeyTyped

    private void camponumerodedocumento2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_camponumerodedocumento2KeyTyped

    }//GEN-LAST:event_camponumerodedocumento2KeyTyped

    private void camposexo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_camposexo2ItemStateChanged

    }//GEN-LAST:event_camposexo2ItemStateChanged

    private void campocorreopersonal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campocorreopersonal2KeyTyped

    }//GEN-LAST:event_campocorreopersonal2KeyTyped

    private void botoncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelar1ActionPerformed
        //limpiar evento
        avisonombre.setText("");
        avisoprimerapellido.setText("");
        avisosegundoapellido.setText("");
        avisonumerodocumento.setText("");
        avisocorreopersonal1.setText("");
        avisocodigoestudiantil.setText("");
        avisoestado.setText("");
        //limpiar componentes
        camponombre2.setText("");
        camposegundonombre1.setText("");
        campoprimerapellido1.setText("");
        camposegundoapellido1.setText("");
        camponumerodedocumento.setText("");
        campocorreopersonal.setText("");
        codigo_estudiante1.setText("");
        estado1.setText("");
        campocorreopersonal.setText("");
    }//GEN-LAST:event_botoncancelar1ActionPerformed
    public void validacionCaracteres(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 32 && evento.getKeyChar() <= 64 || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 96 || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 208 || evento.getKeyChar() >= 210 && evento.getKeyChar() <= 240 || evento.getKeyChar() >= 242 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(null, "No se permiten caracteres especiales: '" + evento.getKeyChar() + "'");
        }

    }

    public boolean validarCamposVacios() {
        boolean vacio = false;
        //limpiar
        avisonombre.setText("");
        avisoprimerapellido.setText("");
        avisosegundoapellido.setText("");
        avisonumerodocumento.setText("");
        avisocorreopersonal1.setText("");
        avisocodigoestudiantil.setText("");
        avisoestado.setText("");
        if (camponombre2.getText().isEmpty()) {
            avisonombre.setText("**");
            vacio = true;
        }
        if (campoprimerapellido1.getText().isEmpty()) {
            avisoprimerapellido.setText("**");
            vacio = true;
        }
        if (camposegundoapellido1.getText().isEmpty()) {
            avisosegundoapellido.setText("**");
            vacio = true;
        }
        if (camponumerodedocumento2.getText().isEmpty()) {
            avisonumerodocumento.setText("**");
            vacio = true;
        }
        if (campocorreopersonal2.getText().isEmpty()) {
            avisocorreopersonal1.setText("**");
            vacio = true;
        } else if (!campocorreopersonal2.getText().contains("@") || !campocorreopersonal2.getText().contains(".")) {
            avisocorreopersonal1.setText("No válido.");
        }
        if (estado1.getText().isEmpty()) {
            avisoestado.setText("**");
            vacio = true;
        }
        if (codigo_estudiante1.getText().isEmpty()) {
            avisocodigoestudiantil.setText("**");
            vacio = true;
        }
        return vacio;
    }

    public void validarCorreo(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 32 && evento.getKeyChar() <= 44 || evento.getKeyChar() == 47 || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 63 || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 94 || evento.getKeyChar() == 96 || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 255) {
        }
        evento.consume();
        JOptionPane.showMessageDialog(null, "No se permite ese caracter en específico");
    }
    private void botonguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardar1ActionPerformed
        boolean bandera = validarCamposVacios();
        if (!bandera) {
            Estudiante est = new Estudiante();
            //obtenemos la informacion

            Date fecha = fecha1.getDate();

            DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String fecha_ingreso = formato.format(fecha);

            int año = fecha1.getCalendar().get(Calendar.YEAR);

            String nombre_1 = camponombre2.getText();
            String nombre_2 = camposegundonombre1.getText();
            String apellido_1 = campoprimerapellido1.getText();
            String apellido_2 = camposegundoapellido1.getText();
            String num_documento = camponumerodedocumento2.getText();
            String tipo_documento = campotipodedocumento2.getSelectedItem().toString();
            int edad_est = Integer.parseInt(edad_estudiante1.getValue().toString());
            String Sexo = camposexo2.getSelectedItem().toString();
            String Programa = campoprograma1.getSelectedItem().toString();

            String correo_personal = campocorreopersonal2.getText();

            int codigo_est = Integer.parseInt(codigo_estudiante1.getText());
            //System.out.println(codigo_est);
            String Estado = estado1.getText();
            int periodo = Integer.parseInt(periodo_ingreso1.getValue().toString());

            //hacemos las validacones
            String correo_institucional = est.validar_correo_institucional(nombre_1, apellido_1, apellido_2, objconexion);
            // boolean validacion_correo= est.validar_correo_institucional(correo_institucional);

            est.cargar_estudiantes(nombre_1, nombre_2, apellido_1, apellido_2, tipo_documento, num_documento, edad_est, Sexo, correo_personal, correo_institucional, codigo_est, Estado, Programa, año, periodo, fecha_ingreso, objconexion);

            //limpiamos los componentes despues de haber cargado el estudiante
            camponombre2.setText("");
            camposegundonombre1.setText("");
            campoprimerapellido1.setText("");
            camposegundoapellido1.setText("");
            camponumerodedocumento.setText("");
            campocorreopersonal.setText("");
            codigo_estudiante1.setText("");
            estado1.setText("");
            campocorreopersonal2.setText("");
        } else {

            JOptionPane.showMessageDialog(null, "Digite los campos obligatorios (**).");
        }
    }//GEN-LAST:event_botonguardar1ActionPerformed

    private void codigo_estudiante1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_estudiante1KeyTyped

    }//GEN-LAST:event_codigo_estudiante1KeyTyped

    private void estado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado1ActionPerformed

    private void estado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estado1KeyTyped
        validacionCaracteres(evt);
    }//GEN-LAST:event_estado1KeyTyped

    private void botoncontacto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncontacto1ActionPerformed
        JOptionPane.showMessageDialog(null, "Correo: sacru@unillanos.edu.co");
    }//GEN-LAST:event_botoncontacto1ActionPerformed

    private void botonayuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonayuda1ActionPerformed
        JOptionPane.showMessageDialog(null, "Correo sacru@unillanos.edu.co");
    }//GEN-LAST:event_botonayuda1ActionPerformed

    private void botonayuda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonayuda3ActionPerformed
        JOptionPane.showMessageDialog(null, "Correo sacru@unillanos.edu.co");
    }//GEN-LAST:event_botonayuda3ActionPerformed

    private void botonayuda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonayuda6ActionPerformed
        JOptionPane.showMessageDialog(null, "Correo sacru@unillanos.edu.co");
    }//GEN-LAST:event_botonayuda6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioadministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioadministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioadministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioadministrador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioadministrador1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scrollpanedetabla;
    private javax.swing.JLabel agregarestudiantes1;
    private javax.swing.JLabel avisocodigoestudiantil;
    private javax.swing.JLabel avisocorreopersonal1;
    private javax.swing.JLabel avisoestado;
    private javax.swing.JLabel avisonombre;
    private javax.swing.JLabel avisonumerodocumento;
    private javax.swing.JLabel avisoprimerapellido;
    private javax.swing.JLabel avisosegundoapellido;
    private javax.swing.JButton botonayuda1;
    private javax.swing.JButton botonayuda3;
    private javax.swing.JButton botonayuda6;
    private javax.swing.JButton botoncancelar1;
    private javax.swing.JButton botoncerrarsesion;
    private javax.swing.JButton botonconsultar1;
    private javax.swing.JButton botoncontacto1;
    private javax.swing.JButton botongenerarmatriculaadmin;
    private javax.swing.JButton botonguardar1;
    private javax.swing.JButton botoninfoadmin;
    private javax.swing.JButton botoninicio;
    private javax.swing.JComboBox<String> botonperiodoacademico;
    private javax.swing.JButton botonregistroestudiante;
    private javax.swing.JButton botonvisualizarestudiantes;
    private com.toedter.calendar.JYearChooser botonyear;
    private javax.swing.JTextField buscarporcodigos1;
    private javax.swing.JComboBox<String> buscarporfacultades1;
    private javax.swing.JComboBox<String> buscarporprogramas1;
    private javax.swing.JLabel campocargo;
    private javax.swing.JLabel campocodigo;
    private javax.swing.JLabel campocodigo1;
    private javax.swing.JLabel campocorreoinstitucional;
    private javax.swing.JLabel campocorreopersonal;
    private javax.swing.JTextField campocorreopersonal2;
    private javax.swing.JLabel campoedad;
    private javax.swing.JTextField camponombre2;
    private javax.swing.JLabel camponombreadmin;
    private javax.swing.JLabel camponumerodecelular;
    private javax.swing.JLabel camponumerodedocumento;
    private javax.swing.JTextField camponumerodedocumento2;
    private javax.swing.JTextField campoprimerapellido1;
    private javax.swing.JComboBox<String> campoprograma1;
    private javax.swing.JTextField camposegundoapellido1;
    private javax.swing.JTextField camposegundonombre1;
    private javax.swing.JLabel camposexo;
    private javax.swing.JComboBox<String> camposexo2;
    private javax.swing.JLabel campotipodedocumento;
    private javax.swing.JComboBox<String> campotipodedocumento2;
    private javax.swing.JLabel cargo;
    private javax.swing.JLabel cargousuario;
    private javax.swing.JTextField codigo_estudiante1;
    private javax.swing.JLabel codigoadmin;
    private javax.swing.JLabel correoinstitucional;
    private javax.swing.JLabel correopersonal;
    private javax.swing.JLabel correopersonal2;
    private javax.swing.JLabel derechossacruagregarestudiante1;
    private javax.swing.JLabel derechossacruagregarestudiante2;
    private javax.swing.JLabel derechossacruagregarestudiante3;
    private javax.swing.JLabel derechossacruagregarestudiante4;
    private javax.swing.JLabel derechosutexto2;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel edad2;
    private javax.swing.JSpinner edad_estudiante1;
    private javax.swing.JTextField estado1;
    private com.toedter.calendar.JDateChooser fecha1;
    private javax.swing.JButton generar_matricula;
    private javax.swing.JLabel informacionpersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel label_codigo_est1;
    private javax.swing.JLabel label_estado1;
    private javax.swing.JLabel label_fecha_in1;
    private javax.swing.JLabel label_periodo_in1;
    private javax.swing.JLabel logosacrumenu;
    private javax.swing.JLabel logousuario;
    private javax.swing.JPanel menugeneral;
    private javax.swing.JLabel nombreadmin;
    private javax.swing.JLabel nombreusuario;
    private javax.swing.JLabel numcelularadmin;
    private javax.swing.JLabel numerodedocumento;
    private javax.swing.JLabel numerodedocumento2;
    private javax.swing.JPanel panelderechoblanco;
    private javax.swing.JPanel paneldeusuario;
    private javax.swing.JPanel panelfondoinicioblanco;
    private javax.swing.JPanel panelinfoadmin;
    private javax.swing.JPanel panelinicioregistro1;
    private javax.swing.JPanel panelmatricula;
    private javax.swing.JPanel panelresultadoestudiantes;
    private javax.swing.JSpinner periodo_ingreso1;
    private javax.swing.JLabel primerapellido1;
    private javax.swing.JLabel primernombre1;
    private javax.swing.JLabel programa1;
    private javax.swing.JLabel segundoapellido1;
    private javax.swing.JLabel segundonombre1;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel sexo2;
    private javax.swing.JTable tablaestudiantes;
    private javax.swing.JLabel tipodedocumento;
    private javax.swing.JLabel tipodedocumento2;
    private javax.swing.JLabel titulogenerarmatricula;
    private javax.swing.JLabel titulomenu;
    private javax.swing.JLabel tituloresultadoestudiantes;
    private javax.swing.JLabel titulosacru2;
    private javax.swing.JLabel titulosacru3;
    private javax.swing.JLabel titulosacru4;
    // End of variables declaration//GEN-END:variables
}
