/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Clases.Administrador;
import Clases.Estudiante;
import Clases.Login;
import conexion.conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author xd
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    conexion objconexion = new conexion();
    public static String usuario_online = "";

    public LOGIN() {
        initComponents();
        objconexion.conexiones();
        ///PARA CENTRAR LA VENTANA
        this.setLocationRelativeTo(null);
        ///PARA QUITAR EL MAXIMAR DE LA VENTANA
        this.setResizable(false);
    }
////PARA CAMBIAR EL ICONO DE LA VENTANA

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logosacru2.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoizquierdologin = new javax.swing.JPanel();
        titulosacrulogin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botoningresar = new javax.swing.JButton();
        botonrecuperarcontraseña = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JTextField();
        panelfondologinsacrublanco = new javax.swing.JPanel();
        textoderechossacru = new javax.swing.JLabel();
        fondosacru = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SACRU - Login.");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());

        fondoizquierdologin.setBackground(new java.awt.Color(0, 0, 0));

        titulosacrulogin.setFont(new java.awt.Font("Arial Unicode MS", 0, 36)); // NOI18N
        titulosacrulogin.setForeground(new java.awt.Color(255, 0, 0));
        titulosacrulogin.setText("SACRU");

        botoningresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        botoningresar.setText("Ingresar.");
        botoningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoningresarActionPerformed(evt);
            }
        });

        botonrecuperarcontraseña.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        botonrecuperarcontraseña.setText("Recuperar contraseña.");
        botonrecuperarcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrecuperarcontraseñaActionPerformed(evt);
            }
        });

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoizquierdologinLayout = new javax.swing.GroupLayout(fondoizquierdologin);
        fondoizquierdologin.setLayout(fondoizquierdologinLayout);
        fondoizquierdologinLayout.setHorizontalGroup(
            fondoizquierdologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                .addGroup(fondoizquierdologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                        .addGroup(fondoizquierdologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(botoningresar))
                            .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(fondoizquierdologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titulosacrulogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)))
                            .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(botonrecuperarcontraseña)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fondoizquierdologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contraseña)
                            .addComponent(Usuario))))
                .addContainerGap())
        );
        fondoizquierdologinLayout.setVerticalGroup(
            fondoizquierdologinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoizquierdologinLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(titulosacrulogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoningresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonrecuperarcontraseña)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        panelfondologinsacrublanco.setBackground(new java.awt.Color(255, 255, 255));

        textoderechossacru.setBackground(new java.awt.Color(255, 255, 255));
        textoderechossacru.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textoderechossacru.setText("©2020 Todos los derechos reservados Universidad de los Llanos  Términos - Política de privacidad");

        fondosacru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondologin.png"))); // NOI18N

        javax.swing.GroupLayout panelfondologinsacrublancoLayout = new javax.swing.GroupLayout(panelfondologinsacrublanco);
        panelfondologinsacrublanco.setLayout(panelfondologinsacrublancoLayout);
        panelfondologinsacrublancoLayout.setHorizontalGroup(
            panelfondologinsacrublancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondologinsacrublancoLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(textoderechossacru)
                .addContainerGap())
            .addGroup(panelfondologinsacrublancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondologinsacrublancoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fondosacru)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelfondologinsacrublancoLayout.setVerticalGroup(
            panelfondologinsacrublancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondologinsacrublancoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoderechossacru)
                .addContainerGap())
            .addGroup(panelfondologinsacrublancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondologinsacrublancoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fondosacru)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoizquierdologin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfondologinsacrublanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoizquierdologin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelfondologinsacrublanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoningresarActionPerformed
        Login objlogin = new Login();
        String usuario = Usuario.getText();
        String contraseña = Contraseña.getText();
        boolean entrar = objlogin.validar_usuario(usuario, contraseña, objconexion);
        if (entrar) {
            usuario_online = Usuario.getText();

            boolean tipo = objlogin.tipo_usuario(usuario, objconexion);
            if (tipo) {

                INICIOESTUDIANTE est = new INICIOESTUDIANTE();
//               
//                
//                Estudiante objest = objlogin.obtener_info_estudiante(usuario, objconexion);
//                
//                System.out.println("Soy " + objest.getCodigo());

                est.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "BIENVENIDO ESTUDIANTE.");

            } else {

                inicioadministrador1 estadmin = new inicioadministrador1();
                Administrador objadmin = objlogin.obtener_info_administrador(usuario, objconexion);

//                System.out.println("Hola " + objadmin.getCorreo_personal());
//                System.out.println("Hola " + objadmin.getPeriodo_ingreso());
//                System.out.println("Hola " + objadmin.getAño_ingreso());
                estadmin.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "BIENVENIDO ADMINISTRADOR.");

            }

        } else {

            JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTO.");
        }

    }//GEN-LAST:event_botoningresarActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void botonrecuperarcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrecuperarcontraseñaActionPerformed
        JOptionPane.showMessageDialog(null, "Contraseña enviada a su correo.");
    }//GEN-LAST:event_botonrecuperarcontraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton botoningresar;
    private javax.swing.JButton botonrecuperarcontraseña;
    private javax.swing.JPanel fondoizquierdologin;
    private javax.swing.JLabel fondosacru;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelfondologinsacrublanco;
    private javax.swing.JLabel textoderechossacru;
    private javax.swing.JLabel titulosacrulogin;
    // End of variables declaration//GEN-END:variables
}
